export const uiEditorCompSource = String.raw`-- Generated by UIEditor shared base; game business classes belong outside Generated.
local FX = _G.FX
local UI = FX.Class("CUIEditorUICompClass", "FCUICompClass")

-- 界面定义统一以 1280×720 编辑，设备上等比居中适配且保留节点路径。
function UI:Ctor(owner)
    UI.Super.Ctor(self, owner)
    self:_AdaptToScreen(self:GetRootNode())
end

function UI:_AdaptToScreen(screen)
    local groups = {}
    self._responsiveGroups = groups
    local function restore(child)
        local entry = groups[child]
        if not entry then return end
        child.Position, child.Size = entry.position, entry.size
        entry.scale.Scale = entry.baseScale
        if entry.created then entry.scale:Destroy() end
        groups[child] = nil
    end
    local function update()
        local size = screen.AbsoluteSize
        if size.X <= 0 or size.Y <= 0 then return end
        local factor = math.min(size.X / 1280, size.Y / 720)
        local left, top = (size.X - 1280 * factor) / 2, (size.Y - 720 * factor) / 2
        for child, entry in pairs(groups) do
            local position, dimensions = entry.position, entry.size
            child.Position = UDim2.fromOffset(left + (1280 * position.X.Scale + position.X.Offset) * factor,
                top + (720 * position.Y.Scale + position.Y.Offset) * factor)
            child.Size = UDim2.fromOffset(1280 * dimensions.X.Scale + dimensions.X.Offset,
                720 * dimensions.Y.Scale + dimensions.Y.Offset)
            entry.scale.Scale = entry.baseScale * factor
        end
    end
    local function register(child)
        if not child:IsA("GuiObject") or groups[child] then return end
        local scale = child:FindFirstChildOfClass("UIScale")
        local created = not scale
        if created then
            scale = Instance.new("UIScale")
            scale.Name = "UIEditorResponsiveScale"
            scale.Parent = child
        end
        groups[child] = { position = child.Position, size = child.Size,
            scale = scale, baseScale = scale.Scale, created = created }
        update()
    end
    for _, child in ipairs(screen:GetChildren()) do register(child) end
    self._restoreResponsiveGroup = restore
    self:TrackConnection(screen:GetPropertyChangedSignal("AbsoluteSize"):Connect(update))
    self:TrackConnection(screen.ChildAdded:Connect(register))
    self:TrackConnection(screen.ChildRemoved:Connect(restore))
end

-- 先断开监听，再恢复设计值，防止组件再次创建时累积缩放。
function UI:Dtor()
    UI.Super.Dtor(self)
    if self._responsiveGroups then
        for child in pairs(self._responsiveGroups) do self._restoreResponsiveGroup(child) end
        self._responsiveGroups = nil
        self._restoreResponsiveGroup = nil
    end
end

--- 使用导出包的 ScreenGui 名称，业务子类可覆写组件名。
--- @return string 此界面的组件名。
function UI:GetCompName()
    return self.ScreenGuiName .. "Comp"
end

--- 首次访问时取得导入的 PlayerGui 界面，不重新创建视觉节点。
--- @return ScreenGui 当前玩家的界面根节点。
function UI:GetRootNode()
    if not self._rootNode then
        self._rootNode = FX.Loader:PlayerGui(self.ScreenGuiName)
    end
    return self._rootNode
end

--- @return table 接入子类提供的配置。
function UI:GetUIConfig()
    return self.Config
end

--- @return table 接入子类提供的状态。
function UI:GetUIState()
    return self.State
end

--- 数据订阅由业务子类覆写，默认刷新一次。
function UI:BindUIData()
    self:RefreshUI()
end

--- 将状态交给界面展示类，防止递归刷新。
function UI:RefreshUI()
    assert(not self._uiRendering, "Recursive RefreshUI is not allowed")
    self._uiRendering = true
    local ok, err = pcall(function()
        if self.Render then
            self:Render(self:GetUIState())
        end
    end)
    self._uiRendering = false
    if not ok then
        error(err, 0)
    end
end

--- 仅转发动作，不执行发奖或资格判断。
--- @param action string 非空动作名。
--- @param payload table 必要业务标识。
function UI:EmitUIAction(action, payload)
    assert(type(action) == "string" and #action > 0, "Expected action name")
    self:OnUIAction(action, payload)
end

--- 默认不处理业务，由接入子类覆写。
--- @param action string 展示层动作名，保留供业务覆写。
--- @param payload table 展示层业务参数，保留供业务覆写。
function UI:OnUIAction(action, payload)
end

--- 原生禁用阻止按钮激活，不改变业务状态。
--- @param button GuiButton 要更新的按钮。
--- @param enabled boolean 是否允许 Activated。
function UI:SetButtonEnabled(button, enabled)
    button.Interactable = enabled
end

return UI
`;
