import { _electron as electron } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir, mkdtemp, readFile } from 'node:fs/promises';
import { resolve, join } from 'node:path';

const packaged = process.argv.includes('--packaged');
await mkdir(resolve('test-results'), { recursive: true });
const root = await mkdtemp(resolve('test-results/runtime-smoke-'));
const parent = join(root, 'project'); await mkdir(parent);
const file = join(parent, 'UIEditorWorkspace/interfaces/reward.rbxui.json');
const env = { ...process.env, UI_EDITOR_USER_DATA: join(root, 'runtime') }; delete env.ELECTRON_RUN_AS_NODE;
const app = await electron.launch(packaged
  ? { executablePath: resolve('../ToolRuntime/UIEditor-win32-x64/UIEditor.exe'), env }
  : { args: ['.'], env });
async function setScript(value) {
  const source = page.getByRole('textbox', { name: '交互脚本', exact: true });
  await source.focus();
  await page.keyboard.press('Control+a');
  await page.keyboard.insertText(value);
}
let page;
try {
  page = await app.firstWindow();
  if (packaged) await page.context().setOffline(true);
  page.setDefaultTimeout(10000);
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.evaluate(() => { window.confirm = () => true; });
  await app.evaluate(({ dialog }, options) => {
    dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [options.parent] });
    dialog.showSaveDialog = async () => ({ canceled: false, filePath: options.file });
    dialog.showMessageBox = async () => ({ response: 0 });
  }, { parent, file });
  await page.getByRole('button', { name: '创建工程', exact: true }).click();
  assert.equal(await page.getByRole('button', { name: 'UI 资产', exact: true }).getAttribute('aria-pressed'), 'true');
  assert.equal(await page.getByRole('log').isVisible(), false);
  await page.getByRole('button', { name: '文件', exact: true }).click();
  await page.getByRole('button', { name: '新建界面', exact: true }).click();
  const newName = page.getByRole('textbox', { name: '新界面名称', exact: true });
  for (const name of ['在线奖励', '2Reward', 'end']) {
    await newName.fill(name);
    assert.equal(await page.getByRole('button', { name: '创建', exact: true }).isEnabled(), false);
  }
  await page.getByRole('button', { name: '取消', exact: true }).click();
  await page.getByText('请打开一个工程', { exact: true }).waitFor();
  await page.getByRole('button', { name: '文件', exact: true }).click();
  await page.getByRole('button', { name: '新建界面', exact: true }).click();
  await newName.fill('OnlineReward');
  await page.getByText('交互类：COnlineRewardUIBaseCompClass', { exact: true }).waitFor();
  await page.getByRole('button', { name: '创建', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('[aria-label="界面名称"]')?.value === 'OnlineReward');
  await page.getByRole('button', { name: '交互脚本', exact: true }).click();
  await page.getByRole('button', { name: '文件', exact: true }).click();
  await page.getByRole('button', { name: '保存', exact: true }).click();
  await page.getByText('界面已保存', { exact: true }).waitFor();
  const template = JSON.parse(await readFile(file, 'utf8'));
  assert.match(template.scripts.source, /COnlineRewardUIBaseCompClass/);
  assert.match(template.scripts.integration, /COnlineRewardUIPreviewCompClass/);
  assert.doesNotMatch(template.scripts.integration, /print\(/);
  const tokenColors = await page.locator('[aria-label="交互脚本面板"] .view-lines span').evaluateAll(spans => [...new Set(spans.map(span => getComputedStyle(span).color))]);
  assert.ok(tokenColors.length >= 3, JSON.stringify(tokenColors));
  await page.screenshot({ path: resolve('test-results/named-script-highlight.png') });
  await setScript('-- highlight test\nlocal count = 123\n' + template.scripts.source);
  await page.getByRole('button', { name: '文件', exact: true }).click();
  await page.getByRole('button', { name: '保存', exact: true }).click();
  await page.getByText('界面已保存', { exact: true }).waitFor();
  assert.match(JSON.parse(await readFile(file, 'utf8')).scripts.source, /local count = 123/);
  await page.getByRole('textbox', { name: '交互脚本', exact: true }).focus();
  await page.keyboard.press('Control+z');
  await page.getByText('界面有未保存修改', { exact: true }).waitFor();
  await page.getByRole('button', { name: '编辑', exact: true }).click();
  await page.getByRole('button', { name: /重做/ }).click();
  await page.getByText('界面已保存', { exact: true }).waitFor();
  await page.getByRole('button', { name: '运行', exact: true }).click();
  await page.getByRole('button', { name: '重置', exact: true }).waitFor({ state: 'visible' });
  await page.waitForFunction(() => !document.querySelector('.runtime-toolbar button:last-child')?.disabled);
  await page.getByRole('button', { name: '停止', exact: true }).click();
  await page.getByRole('button', { name: '交互脚本', exact: true }).click();
  await page.getByRole('button', { name: '载入奖励示例', exact: true }).click();
  await page.getByRole('button', { name: '文件', exact: true }).click();
  await page.getByRole('button', { name: '保存', exact: true }).click();
  await page.getByText('界面已保存', { exact: true }).waitFor();
  const saved = JSON.parse(await readFile(file, 'utf8'));
  const original = await readFile(file, 'utf8');
  assert.equal(saved.version, 3);
  assert.match(saved.scripts.source, /function UI:Render/);
  assert.match(saved.scripts.integration, /function Preview:OnUIAction/);
  assert.deepEqual(Object.keys(saved.scripts).sort(), ['integration', 'source']);
  assert.equal(await page.locator('.script-tabs').count(), 0);
  assert.equal(await page.getByRole('button', { name: '配置脚本', exact: true }).count(), 0);
  assert.equal(await page.getByRole('button', { name: '节点引用', exact: true }).count(), 0);
  assert.equal(await page.getByRole('button', { name: '模拟状态', exact: true }).count(), 0);
  for (let cycle = 0; cycle < 2; cycle++) {
    await page.getByRole('button', { name: '运行', exact: true }).click();
    const button = page.getByRole('button', { name: 'ClaimButton', exact: true });
    await button.waitFor();
    await page.waitForFunction(() => document.querySelector('[role="button"][aria-label="ClaimButton"]')?.getAttribute('aria-disabled') === 'false');
    assert.equal(await button.getAttribute('aria-disabled'), 'false');
    assert.equal(await button.evaluate(node => getComputedStyle(node).cursor), 'pointer');
    const passiveNodes = page.getByTestId('ui-artboard').locator('.preview-node:not([role="button"])');
    assert.ok(await passiveNodes.count() > 0);
    assert.ok((await passiveNodes.evaluateAll(nodes => nodes.map(node => getComputedStyle(node).cursor))).every(cursor => cursor === 'default'), '运行中的普通节点应显示正常光标');
    const label = page.getByTestId('ui-artboard').locator('.preview-node[data-class-name="TextLabel"]').first();
    const beforeDrag = await page.getByTestId('ui-artboard').locator('.preview-node').evaluateAll(nodes => nodes.map(node => ({ id: node.dataset.nodeId, style: node.getAttribute('style') })));
    const bounds = await label.boundingBox();
    assert.ok(bounds);
    await page.mouse.move(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2);
    await page.mouse.down();
    await page.mouse.move(bounds.x + bounds.width / 2 + 30, bounds.y + bounds.height / 2 + 20, { steps: 5 });
    await page.mouse.up();
    assert.deepEqual(await page.getByTestId('ui-artboard').locator('.preview-node').evaluateAll(nodes => nodes.map(node => ({ id: node.dataset.nodeId, style: node.getAttribute('style') }))), beforeDrag, '运行中拖动不得改变节点');
    const controls = await page.locator('.workspace-editor .runtime-toolbar').boundingBox();
    const tabs = await page.locator('.workspace-tabs').boundingBox();
    assert.ok(controls && tabs && controls.y + controls.height <= tabs.y && controls.x === tabs.x, '运行控制应位于工作区页签上方');
    assert.equal(await page.locator('.runtime-toolbar button').count(), 4);
    assert.equal(await page.getByRole('button', { name: '运行', exact: true }).count(), 0);
    await page.getByRole('button', { name: '隐藏', exact: true }).click();
    await button.waitFor({ state: 'hidden' });
    assert.equal(await page.getByRole('button', { name: '停止', exact: true }).isEnabled(), true);
    await page.getByRole('button', { name: '打开', exact: true }).click();
    await button.waitFor({ state: 'visible' });
    assert.equal(await page.locator('.node-selection').count(), 0);
    assert.equal(await page.getByRole('button', { name: '适应窗口', exact: true }).isEnabled(), true);
    await page.getByRole('button', { name: '交互脚本', exact: true }).click();
    assert.equal(await page.getByRole('textbox', { name: '交互脚本', exact: true }).getAttribute('readonly'), 'true');
    await page.getByRole('button', { name: '接入脚本', exact: true }).click();
    assert.equal(await page.getByRole('textbox', { name: '接入脚本', exact: true }).getAttribute('readonly'), 'true');
    await page.getByRole('button', { name: '界面', exact: true }).click();
    try { await button.click(); } catch (error) {
      console.log('Runtime click geometry', await button.boundingBox(), await page.locator('.canvas-viewport').boundingBox(), await page.evaluate(() => ({ width: innerWidth, height: innerHeight })));
      await page.screenshot({ path: resolve('test-results/runtime-click-failure.png') });
      throw error;
    }
    await page.getByRole('button', { name: '输出', exact: true }).click();
    await page.getByRole('log').getByText(/ClaimReward.*online_5min/).waitFor();
    assert.equal(await page.getByRole('log').locator('.action').count(), 1);
    await page.getByRole('log').getByText(/模拟领取.*online_5min/).waitFor();
    await page.getByRole('button', { name: 'UI 资产', exact: true }).click();
    assert.equal(await page.getByRole('log').isVisible(), false);
    await page.getByRole('navigation', { name: '资产库', exact: true }).waitFor();
    await page.getByRole('button', { name: '输出', exact: true }).click();
    assert.equal(await page.getByRole('log').locator('.action').count(), 1);
    await page.waitForFunction(() => document.querySelector('[role="button"][aria-label="ClaimButton"]')?.textContent === 'Claimed');
    assert.equal(await button.evaluate(node => getComputedStyle(node).cursor), 'not-allowed');
    await page.getByRole('button', { name: '隐藏', exact: true }).click();
    await button.waitFor({ state: 'hidden' });
    await page.getByRole('button', { name: '打开', exact: true }).click();
    await button.waitFor({ state: 'visible' });
    assert.equal(await button.textContent(), 'Claimed');
    await page.getByRole('button', { name: '接入脚本', exact: true }).click();
    await page.getByRole('button', { name: '重置', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('[role="button"][aria-label="ClaimButton"]')?.getAttribute('aria-disabled') === 'false');
    await page.getByRole('button', { name: '界面', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('[role="button"][aria-label="ClaimButton"]')?.getAttribute('aria-disabled') === 'false');
    await page.getByRole('button', { name: '停止', exact: true }).click();
    await page.getByRole('button', { name: '运行', exact: true }).waitFor({ state: 'visible' });
    assert.equal(await page.locator('.runtime-toolbar button').count(), 1);
    assert.equal(await page.getByRole('button', { name: 'ClaimButton', exact: true }).count(), 0);
    assert.equal(await readFile(file, 'utf8'), original);
    assert.ok((await page.getByTestId('ui-artboard').locator('.preview-node').evaluateAll(nodes => nodes.map(node => getComputedStyle(node).cursor))).every(cursor => cursor === 'move'), '停止后恢复编辑光标');
    await page.getByText('界面已保存', { exact: true }).waitFor();
  }
  await page.getByRole('button', { name: '交互脚本', exact: true }).click();
  const source = page.getByRole('textbox', { name: '交互脚本', exact: true });
  await setScript('print("before-error")\nwarn("before-warning")\nerror("smoke-error")');
  await page.getByRole('button', { name: '运行', exact: true }).click();
  await page.getByRole('log').getByText(/interface:3.*smoke-error/).waitFor();
  await page.getByRole('log').locator('.output').getByText(/before-error/).waitFor();
  await page.getByRole('log').locator('.warning').getByText(/before-warning/).waitFor();
  assert.equal(await page.getByRole('button', { name: '运行', exact: true }).isEnabled(), true);
  await page.getByRole('button', { name: '交互脚本', exact: true }).click();
  assert.equal(await source.getAttribute('readonly'), null);
  await setScript(saved.scripts.source);
  await page.getByRole('button', { name: '运行', exact: true }).click();
  await page.getByRole('button', { name: 'ClaimButton', exact: true }).waitFor();
  await page.waitForFunction(() => document.querySelector('[role="button"][aria-label="ClaimButton"]')?.getAttribute('aria-disabled') === 'false');
  await page.screenshot({ path: resolve(`test-results/${packaged ? 'packaged-' : ''}runtime.png`) });
  await page.getByRole('button', { name: '接入脚本', exact: true }).click();
  await page.screenshot({ path: resolve(`test-results/${packaged ? 'packaged-' : ''}integration.png`) });
  await page.getByRole('button', { name: '停止', exact: true }).click();
  assert.deepEqual(errors, []);
  console.log(`PASS: ${packaged ? 'packaged offline' : 'development'} Luau, class inheritance, button action, integration state, reset, errors, read-only design, clean stop.`);
} finally { await app.close(); }
