import { lstat, readFile, writeFile } from 'node:fs/promises';
import { isAbsolute, join } from 'node:path';

const MARKER = 'rem Generated by UIEditor.';

async function readRegularFile(path: string): Promise<string | null> {
  try {
    if (!(await lstat(path)).isFile()) throw new Error(`启动文件不能是目录或符号链接：${path}`);
    return await readFile(path, 'utf8');
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null;
    throw error;
  }
}

export async function ensureWorkspaceLauncher(workspacePath: string, executablePath: string, applicationPath?: string): Promise<void> {
  if (![workspacePath, executablePath, ...(applicationPath ? [applicationPath] : [])].every(isAbsolute)) throw new Error('启动路径必须是绝对路径。');
  const launcherPath = join(workspacePath, 'Run.bat');
  const existing = await readRegularFile(launcherPath);
  if (existing !== null && !existing.includes(MARKER)) throw new Error('工作区已有非自动生成的 Run.bat，请先改名后重新打开工作区。');
  const ignorePath = join(workspacePath, '.gitignore');
  const ignore = await readRegularFile(ignorePath) ?? '';
  const quotePath = (path: string) => `"${path.replace(/%/g, '%%')}"`;
  const script = [
    '@echo off', 'chcp 65001 >nul', 'setlocal DisableDelayedExpansion', MARKER,
    'set "UI_EDITOR_OPEN_WORKSPACE=%~dp0"',
    `set "UI_EDITOR_EXE=${executablePath.replace(/%/g, '%%')}"`,
    'if not exist "%UI_EDITOR_EXE%" (',
    '  echo UIEditor was not found. Reopen this workspace in the editor to regenerate Run.bat.',
    '  pause', '  exit /b 1', ')',
    `start "" /wait "%UI_EDITOR_EXE%"${applicationPath ? ` ${quotePath(applicationPath)}` : ''}`,
    'set "EXIT_CODE=%ERRORLEVEL%"',
    'if not "%EXIT_CODE%"=="0" pause', 'exit /b %EXIT_CODE%', '',
  ].join('\r\n');
  await writeFile(launcherPath, script, 'utf8');
  if (!ignore.split(/\r?\n/).some(line => line.trim() === '/Run.bat')) {
    await writeFile(ignorePath, `${ignore}${ignore && !ignore.endsWith('\n') ? '\n' : ''}/Run.bat\n`, 'utf8');
  }
}
